### ISSUE TITLE
Webhook Fliter Checklist

### ISSUE THREAD

**Issue by Snazzah** [trello-talk/TrelloBot#44]
This is half of me keeping track of what events I have finished being read on the new webhook and half showing progress of the rewrite.

## Filters
* [x] ADD_ATTACHMENT_TO_CARD
* [x] ADD_CHECKLIST_TO_CARD
* [x] ADD_LABEL_TO_CARD
* [x] ADD_MEMBER_TO_BOARD
* [x] ADD_MEMBER_TO_CARD
* [x] COMMENT_CARD
* [x] CONVERT_TO_CARD_FROM_CHECK_ITEM
* [x] COPY_CARD
* [x] COPY_CHECKLIST
* [x] CREATE_LABEL
* [x] CREATE_CARD
* [x] CREATE_LIST
* [x] DELETE_ATTACHMENT_FROM_CARD
* [x] DELETE_CARD
* [x] DELETE_CHECK_ITEM
* [x] DELETE_LABEL
* [x] ~~DISABLE_PLUGIN~~
* [x] ~~DISABLE_POWER_UP~~
* [x] ~~ENABLE_PLUGIN~~
* [x] ~~ENABLE_POWER_UP~~
* [x] MAKE_ADMIN_OF_BOARD
* [x] MAKE_NORMAL_MEMBER_OF_BOARD
* [x] MOVE_CARD_FROM_BOARD
* [x] MOVE_CARD_TO_BOARD:
* [x] MOVE_LIST_FROM_BOARD
* [x] MOVE_LIST_TO_BOARD
* [x] REMOVE_CHECKLIST_FROM_CARD
* [x] REMOVE_LABEL_FROM_CARD
* [x] REMOVE_MEMBER_FROM_BOARD
* [x] REMOVE_MEMBER_FROM_CARD
* [x] UPDATE_CHECK_ITEM_STATE_ON_CARD
* [x] VOTE_ON_CARD
* [x] CREATE_CHECK_ITEM
* [x] DELETE_COMMENT
* [x] UPDATE_COMMENT

UPDATE_BOARD
* [x] UPDATE_BOARD_NAME
* [x] UPDATE_BOARD_DESC
* [x] UPDATE_BOARD_PREFS
* [x] UPDATE_BOARD_CLOSED

UPDATE_CARD
* [x] UPDATE_CARD_NAME
* [x] UPDATE_CARD_DESC
* [x] UPDATE_CARD_LIST
* [x] UPDATE_CARD_POS
* [x] UPDATE_CARD_CLOSED
* [x] UPDATE_CARD_DUE

UPDATE_CHECK_ITEM
* [x] UPDATE_CHECK_ITEM_NAME
* [x] UPDATE_CHECK_ITEM_POS

UPDATE_CHECKLIST
* [x] UPDATE_CHECKLIST_NAME
* [x] UPDATE_CHECKLIST_POS

UPDATE_LABEL
* [x] UPDATE_LABEL_NAME
* [x] UPDATE_LABEL_COLOR

UPDATE_LIST
* [x] UPDATE_LIST_NAME
* [x] UPDATE_LIST_POS
* [x] UPDATE_LIST_CLOSED
